name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Restore
        run: dotnet restore ./src
      - name: Build
        run: dotnet build ./src
      - name: Test
        run: dotnet test ./src
