name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      - name: Setup Validator
        run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.304
      - name: Restore
        run: dotnet restore ./src
      - name: Build
        run: dotnet build ./src
      - name: Test
        run: dotnet test ./src
      - name: Pack
        run: dotnet pack ./src/SwarmFit/ -o packages
      - name: Validate Packages
        run: dotnet validate package local ./packages/*.nupkg
      - name: Setup NuGet
        if: github.ref == 'refs/heads/main'
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Deploy NuGet Packages
        if: github.ref == 'refs/heads/main'
        run: nuget push packages/*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json